global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.19.0.11:8000'] # Gradio metrics

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.19.0.11:9100'] # Node Exporter